# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be08ec147dace0a73fee096e4a6e9ca8"
application_url = "https://redo-ia4o.onrender.com"
embedded = true
name = "redo"
handle = "redo"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, read_metaobjects, write_metaobjects"

[auth]
redirect_urls = [
  "https://redo-ia4o.onrender.com/auth/callback",
  "https://redo-ia4o.onrender.com/auth/shopify/callback",
  "https://redo-ia4o.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-e5f7c1c4.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
