# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "708f07c2891cb905e819aee828b31e64"
application_url = "https://ai-agent-iuss.onrender.com"
embedded = true
name = "Ai-Agent"
handle = "ai-agent-14"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://ai-agent-iuss.onrender.com/api/auth" ]

[pos]
embedded = false
